version: '3'
services:
  minio:
    container_name: observability-minio
    image: minio/minio:RELEASE.2017-08-05T00-00-53Z
    command: server /export
    environment:
    - MINIO_ACCESS_KEY=observability_access
    - MINIO_SECRET_KEY=observability_secret
    ports:
    - 9000:9000
    
  jaeger:
    container_name: observability-jaeger 
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
    - 16686:16686
    - 5778:5778
    - 6831:6831/udp
    - 14268:14268